/* Generated by DomainHarness. DO NOT EDIT. */
export const APP_CONTRACT_FORMAT = "domain-harness.app-contracts.v1" as const;

export type Schema_OrderChangedEvent = { readonly "orderId": string; readonly "status": "pending" | "accepted" | "rejected" };
export type Schema_OrderSummary = { readonly "amount": number; readonly "orderId": string; readonly "status": "pending" | "accepted" | "rejected" };
export type Schema_OrderViewInput = { readonly "orderId": string };
export type Schema_SubmitOrderOutcome = ({ readonly "sequence": number; readonly "status": "accepted" }) | ({ readonly "reason": string; readonly "status": "rejected" });
export type Schema_SubmitOrderPayload = { readonly "amount": number; readonly "orderId": string; readonly "tags"?: readonly (string)[] };

export interface AppCommandMap {
  readonly "submitOrder": {
    readonly payload: Schema_SubmitOrderPayload;
    readonly outcome: Schema_SubmitOrderOutcome;
  };
}
export type AppCommandId = keyof AppCommandMap;
export type AppCommand<T extends AppCommandId = AppCommandId> = T extends AppCommandId ? {
  readonly commandId: T;
  readonly payload: AppCommandMap[T]["payload"];
} : never;
export type AppCommandOutcome<T extends AppCommandId = AppCommandId> =
  T extends AppCommandId ? AppCommandMap[T]["outcome"] : never;

export interface AppViewMap {
  readonly "orderSummary": {
    readonly input: Schema_OrderViewInput;
    readonly output: Schema_OrderSummary;
  };
}
export type AppViewId = keyof AppViewMap;
export type AppViewRequest<T extends AppViewId = AppViewId> = T extends AppViewId ? {
  readonly viewId: T;
  readonly input: AppViewMap[T]["input"];
} : never;
export type AppViewResult<T extends AppViewId = AppViewId> =
  T extends AppViewId ? AppViewMap[T]["output"] : never;

export interface AppWatchMap {
  readonly "watchOrderSummary": {
    readonly input: AppViewMap["orderSummary"]["input"];
    readonly value: AppViewMap["orderSummary"]["output"];
  };
}
export type AppWatchId = keyof AppWatchMap;
export type AppWatchRequest<T extends AppWatchId = AppWatchId> = T extends AppWatchId ? {
  readonly watchId: T;
  readonly input: AppWatchMap[T]["input"];
} : never;
export type AppWatchValue<T extends AppWatchId = AppWatchId> =
  T extends AppWatchId ? AppWatchMap[T]["value"] : never;

export interface AppDomainEventMap {
  readonly "orderChanged": Schema_OrderChangedEvent;
}
export type AppDomainEventId = keyof AppDomainEventMap;
export type AppDomainEvent<T extends AppDomainEventId = AppDomainEventId> = T extends AppDomainEventId ? {
  readonly type: T;
  readonly payload: AppDomainEventMap[T];
} : never;

