import { assertCompiledPackageManifest, type CompiledPackageManifest } from './manifest.js';

export interface BindingModuleReference {
  moduleSpecifier: string;
  exportName?: string;
}

export interface EmitTargetModuleInput {
  manifest: CompiledPackageManifest;
  bindingModules: Readonly<Record<string, BindingModuleReference>>;
}

function jsString(value: string): string {
  return JSON.stringify(value);
}

export function emitTargetCompiledPackageModule(input: EmitTargetModuleInput): string {
  assertCompiledPackageManifest(input.manifest);
  const bindingIds = Object.keys(input.manifest.bindingDigests).sort();
  const imports: string[] = [];
  const assignments: string[] = [];
  bindingIds.forEach((bindingId, index) => {
    const reference = input.bindingModules[bindingId];
    if (!reference) throw new Error(`no generated module reference supplied for binding '${bindingId}'`);
    if (!reference.moduleSpecifier || /[\r\n\0]/u.test(reference.moduleSpecifier) || /^[a-z][a-z0-9+.-]*:\/\//iu.test(reference.moduleSpecifier)) throw new Error(`invalid module specifier for binding '${bindingId}'`);
    const local = `__binding_${index}`;
    if (reference.exportName) {
      if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(reference.exportName)) throw new Error(`invalid export name '${reference.exportName}' for binding '${bindingId}'`);
      imports.push(`import { ${reference.exportName} as ${local} } from ${jsString(reference.moduleSpecifier)};`);
    } else {
      imports.push(`import ${local} from ${jsString(reference.moduleSpecifier)};`);
    }
    assignments.push(`${jsString(bindingId)}: ${local}`);
  });
  const manifestJson = JSON.stringify(input.manifest, null, 2);
  return [
    '// Generated by @kaicreator/domain-harness-compiler. Do not edit.',
    ...imports,
    '',
    `export const manifest = Object.freeze(${manifestJson});`,
    `export const bindings = Object.freeze({${assignments.join(', ')}});`,
    'const compiledPackage = Object.freeze({ manifest, bindings });',
    'export default compiledPackage;',
    '',
  ].join('\n');
}
