import type { CompiledPackageManifest } from '../v2/contracts/package.js';
import { AppContractGenerationError } from './app-contract-errors.js';
import {
  collectNamedSchemaClosure,
  collectSchemaReferences,
  createSchemaRenderContext,
  renderSchema,
  renderSchemaDeclarations,
  requireSchemaAlias,
} from './app-contract-schema.js';

export { AppContractGenerationError } from './app-contract-errors.js';
export type { AppContractGenerationErrorCode } from './app-contract-errors.js';

export const APP_CONTRACT_SOURCE_FORMAT = 'domain-harness.app-contracts.v1' as const;

export interface AppCommandContractSource {
  readonly commandId: string;
  readonly workflowId: string;
  readonly messageType: string;
  readonly outcomeSchemaId: string;
}

export interface AppViewContractSource {
  readonly viewId: string;
  readonly projectionId: string;
  readonly inputSchemaId: string;
}

export interface AppWatchContractSource {
  readonly watchId: string;
  readonly viewId: string;
}

export interface AppDomainEventContractSource {
  readonly eventId: string;
  readonly workflowId: string;
  readonly messageType: string;
}

/**
 * Build-time selector emitted alongside a target-compiled package. Every schema
 * reference resolves back into the exact compiled manifest; no source/runtime
 * discovery is permitted when an App starts.
 */
export interface CompiledAppContractSource {
  readonly format: typeof APP_CONTRACT_SOURCE_FORMAT;
  readonly packageId: string;
  readonly commands: readonly AppCommandContractSource[];
  readonly views: readonly AppViewContractSource[];
  readonly watches: readonly AppWatchContractSource[];
  readonly domainEvents: readonly AppDomainEventContractSource[];
}

export interface GeneratedAppContractOptions {
  readonly banner?: string;
}

export function generateTypedAppContracts(
  manifest: CompiledPackageManifest,
  source: CompiledAppContractSource,
  options: GeneratedAppContractOptions = {},
): string {
  if (source.format !== APP_CONTRACT_SOURCE_FORMAT) {
    throw new AppContractGenerationError(
      'SOURCE_FORMAT_MISMATCH',
      'source.format',
      `expected ${APP_CONTRACT_SOURCE_FORMAT}, got ${String(source.format)}`,
    );
  }

  if (source.packageId !== manifest.packageId) {
    throw new AppContractGenerationError(
      'PACKAGE_MISMATCH',
      'source.packageId',
      `expected ${manifest.packageId}, got ${source.packageId}`,
    );
  }

  assertUniqueIds(source.commands, 'commandId', 'commands');
  assertUniqueIds(source.views, 'viewId', 'views');
  assertUniqueIds(source.watches, 'watchId', 'watches');
  assertUniqueIds(source.domainEvents, 'eventId', 'domainEvents');

  const publicSchemaIds = collectPublicSchemaIds(manifest, source);
  const context = createSchemaRenderContext(manifest.schemas, publicSchemaIds);
  const lines: string[] = [];
  const banner = options.banner ?? 'Generated by DomainHarness. DO NOT EDIT.';

  lines.push(`/* ${sanitizeComment(banner)} */`);
  lines.push(`export const APP_CONTRACT_FORMAT = ${literal(source.format)} as const;`);
  lines.push('');

  lines.push(...renderSchemaDeclarations(manifest.schemas, context, publicSchemaIds));
  if (publicSchemaIds.size > 0) {
    lines.push('');
  }

  lines.push('export interface AppCommandMap {');
  for (const command of [...source.commands].sort(compareBy('commandId'))) {
    const workflow = manifest.workflows[command.workflowId];
    if (!workflow) {
      throw new AppContractGenerationError(
        'MISSING_WORKFLOW',
        `commands.${command.commandId}.workflowId`,
        command.workflowId,
      );
    }
    const message = workflow.messageContracts[command.messageType];
    if (!message) {
      throw new AppContractGenerationError(
        'MISSING_MESSAGE_CONTRACT',
        `commands.${command.commandId}.messageType`,
        `${command.workflowId}/${command.messageType}`,
      );
    }
    const outcome = requireSchemaAlias(
      manifest.schemas,
      context,
      command.outcomeSchemaId,
      `commands.${command.commandId}.outcomeSchemaId`,
    );
    lines.push(`  readonly ${literal(command.commandId)}: {`);
    lines.push(
      `    readonly payload: ${renderSchema(
        message.payloadSchema,
        context,
        `workflows.${command.workflowId}.messageContracts.${command.messageType}.payloadSchema`,
      )};`,
    );
    lines.push(`    readonly outcome: ${outcome};`);
    lines.push('  };');
  }
  lines.push('}');
  lines.push('export type AppCommandId = keyof AppCommandMap;');
  lines.push(
    'export type AppCommand<T extends AppCommandId = AppCommandId> = T extends AppCommandId ? {',
  );
  lines.push('  readonly commandId: T;');
  lines.push('  readonly payload: AppCommandMap[T]["payload"];');
  lines.push('} : never;');
  lines.push('export type AppCommandOutcome<T extends AppCommandId = AppCommandId> =');
  lines.push('  T extends AppCommandId ? AppCommandMap[T]["outcome"] : never;');
  lines.push('');

  lines.push('export interface AppViewMap {');
  for (const view of [...source.views].sort(compareBy('viewId'))) {
    const projection = manifest.projections[view.projectionId];
    if (!projection) {
      throw new AppContractGenerationError(
        'MISSING_PROJECTION',
        `views.${view.viewId}.projectionId`,
        view.projectionId,
      );
    }
    const input = requireSchemaAlias(
      manifest.schemas,
      context,
      view.inputSchemaId,
      `views.${view.viewId}.inputSchemaId`,
    );
    lines.push(`  readonly ${literal(view.viewId)}: {`);
    lines.push(`    readonly input: ${input};`);
    lines.push(
      `    readonly output: ${renderSchema(
        projection.outputSchema,
        context,
        `projections.${view.projectionId}.outputSchema`,
      )};`,
    );
    lines.push('  };');
  }
  lines.push('}');
  lines.push('export type AppViewId = keyof AppViewMap;');
  lines.push(
    'export type AppViewRequest<T extends AppViewId = AppViewId> = T extends AppViewId ? {',
  );
  lines.push('  readonly viewId: T;');
  lines.push('  readonly input: AppViewMap[T]["input"];');
  lines.push('} : never;');
  lines.push('export type AppViewResult<T extends AppViewId = AppViewId> =');
  lines.push('  T extends AppViewId ? AppViewMap[T]["output"] : never;');
  lines.push('');

  lines.push('export interface AppWatchMap {');
  for (const watch of [...source.watches].sort(compareBy('watchId'))) {
    if (!source.views.some((view) => view.viewId === watch.viewId)) {
      throw new AppContractGenerationError(
        'MISSING_VIEW',
        `watches.${watch.watchId}.viewId`,
        watch.viewId,
      );
    }
    lines.push(`  readonly ${literal(watch.watchId)}: {`);
    lines.push(`    readonly input: AppViewMap[${literal(watch.viewId)}]["input"];`);
    lines.push(`    readonly value: AppViewMap[${literal(watch.viewId)}]["output"];`);
    lines.push('  };');
  }
  lines.push('}');
  lines.push('export type AppWatchId = keyof AppWatchMap;');
  lines.push(
    'export type AppWatchRequest<T extends AppWatchId = AppWatchId> = T extends AppWatchId ? {',
  );
  lines.push('  readonly watchId: T;');
  lines.push('  readonly input: AppWatchMap[T]["input"];');
  lines.push('} : never;');
  lines.push('export type AppWatchValue<T extends AppWatchId = AppWatchId> =');
  lines.push('  T extends AppWatchId ? AppWatchMap[T]["value"] : never;');
  lines.push('');

  lines.push('export interface AppDomainEventMap {');
  for (const event of [...source.domainEvents].sort(compareBy('eventId'))) {
    const workflow = manifest.workflows[event.workflowId];
    if (!workflow) {
      throw new AppContractGenerationError(
        'MISSING_WORKFLOW',
        `domainEvents.${event.eventId}.workflowId`,
        event.workflowId,
      );
    }
    const message = workflow.messageContracts[event.messageType];
    if (!message) {
      throw new AppContractGenerationError(
        'MISSING_MESSAGE_CONTRACT',
        `domainEvents.${event.eventId}.messageType`,
        `${event.workflowId}/${event.messageType}`,
      );
    }
    lines.push(
      `  readonly ${literal(event.eventId)}: ${renderSchema(
        message.payloadSchema,
        context,
        `workflows.${event.workflowId}.messageContracts.${event.messageType}.payloadSchema`,
      )};`,
    );
  }
  lines.push('}');
  lines.push('export type AppDomainEventId = keyof AppDomainEventMap;');
  lines.push(
    'export type AppDomainEvent<T extends AppDomainEventId = AppDomainEventId> = T extends AppDomainEventId ? {',
  );
  lines.push('  readonly type: T;');
  lines.push('  readonly payload: AppDomainEventMap[T];');
  lines.push('} : never;');
  lines.push('');

  return `${lines.join('\n')}\n`;
}

function collectPublicSchemaIds(
  manifest: CompiledPackageManifest,
  source: CompiledAppContractSource,
): ReadonlySet<string> {
  const target = new Set<string>();

  for (const command of source.commands) {
    const workflow = manifest.workflows[command.workflowId];
    if (!workflow) {
      throw new AppContractGenerationError(
        'MISSING_WORKFLOW',
        `commands.${command.commandId}.workflowId`,
        command.workflowId,
      );
    }
    const message = workflow.messageContracts[command.messageType];
    if (!message) {
      throw new AppContractGenerationError(
        'MISSING_MESSAGE_CONTRACT',
        `commands.${command.commandId}.messageType`,
        `${command.workflowId}/${command.messageType}`,
      );
    }
    collectSchemaReferences(
      message.payloadSchema,
      manifest.schemas,
      target,
      `workflows.${command.workflowId}.messageContracts.${command.messageType}.payloadSchema`,
    );
    collectNamedSchemaClosure(
      manifest.schemas,
      command.outcomeSchemaId,
      target,
      `commands.${command.commandId}.outcomeSchemaId`,
    );
  }

  for (const view of source.views) {
    const projection = manifest.projections[view.projectionId];
    if (!projection) {
      throw new AppContractGenerationError(
        'MISSING_PROJECTION',
        `views.${view.viewId}.projectionId`,
        view.projectionId,
      );
    }
    collectNamedSchemaClosure(
      manifest.schemas,
      view.inputSchemaId,
      target,
      `views.${view.viewId}.inputSchemaId`,
    );
    collectSchemaReferences(
      projection.outputSchema,
      manifest.schemas,
      target,
      `projections.${view.projectionId}.outputSchema`,
    );
  }

  for (const event of source.domainEvents) {
    const workflow = manifest.workflows[event.workflowId];
    if (!workflow) {
      throw new AppContractGenerationError(
        'MISSING_WORKFLOW',
        `domainEvents.${event.eventId}.workflowId`,
        event.workflowId,
      );
    }
    const message = workflow.messageContracts[event.messageType];
    if (!message) {
      throw new AppContractGenerationError(
        'MISSING_MESSAGE_CONTRACT',
        `domainEvents.${event.eventId}.messageType`,
        `${event.workflowId}/${event.messageType}`,
      );
    }
    collectSchemaReferences(
      message.payloadSchema,
      manifest.schemas,
      target,
      `workflows.${event.workflowId}.messageContracts.${event.messageType}.payloadSchema`,
    );
  }

  return target;
}

function literal(value: string | number | boolean | null): string {
  return JSON.stringify(value);
}

function sanitizeComment(value: string): string {
  return value.replace(/\*\//g, '* /').replace(/[\r\n]+/g, ' ');
}

function compareBy<K extends string>(
  key: K,
): (left: Record<K, string>, right: Record<K, string>) => number {
  return (left, right) => {
    const leftValue = left[key];
    const rightValue = right[key];
    return leftValue < rightValue ? -1 : leftValue > rightValue ? 1 : 0;
  };
}

function assertUniqueIds<T extends Readonly<Record<K, string>>, K extends keyof T & string>(
  values: readonly T[],
  key: K,
  path: string,
): void {
  const seen = new Set<string>();
  for (const value of values) {
    const id = value[key];
    if (seen.has(id)) {
      throw new AppContractGenerationError('DUPLICATE_CONTRACT_ID', `${path}.${id}`, id);
    }
    seen.add(id);
  }
}
